version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.8
    platform: linux/amd64
    ports:
      - "2181:2181"
    networks:
      - teknasyon_keys_kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - teknasyon_keys_kafka-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - teknasyon_keys_kafka-network
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - teknasyon_keys_kafka-network

networks:
  teknasyon_keys_kafka-network:
    driver: bridge
